# Generated by Django 5.0 on 2023-12-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
