# Generated by Django 5.0 on 2023-12-29 17:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIapp', '0004_posts_date_posts_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
