# Generated by Django 5.0 on 2023-12-29 19:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIapp', '0005_posts_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='liked_posts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, null=True, size=None),
        ),
    ]
