# Generated by Django 5.0 on 2024-01-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIapp', '0007_alter_users_liked_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='img',
            field=models.ImageField(default=False, upload_to='images'),
        ),
    ]
