# Generated by Django 5.0 on 2024-01-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIapp', '0008_posts_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='img',
            field=models.ImageField(default=False, upload_to='media'),
        ),
    ]
