# Generated by Django 5.0 on 2024-01-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIapp', '0009_alter_posts_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profilePicture',
            field=models.ImageField(default='media\\pfp.png', upload_to='media'),
        ),
    ]
