# Generated by Django 5.0 on 2024-01-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIapp', '0010_users_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='bio',
            field=models.CharField(default='user has no bio', max_length=100),
        ),
    ]
