# Generated by Django 5.0 on 2024-01-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIapp', '0013_alter_posts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='followers',
            field=models.IntegerField(default=0),
        ),
    ]
