# Generated by Django 5.0 on 2024-02-20 14:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIapp', '0017_customuser_blocklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('phone', models.IntegerField(null=True)),
                ('joined_date', models.DateField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='liked_posts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=[], max_length=100), blank=True, size=None),
        ),
    ]
