# Generated by Django 5.0 on 2024-02-20 14:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIapp', '0019_delete_users_customuser_userreports_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='blockList',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='followedUsers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, null=True, size=None),
        ),
    ]
